### ISSUE TITLE
Test UI Topic

### ISSUE THREAD

**Issue by vobachnhac1** [vobachnhac1/cb-web#14]

**Comment by aloha1604** [comment]
![image](https://user-images.githubusercontent.com/46180709/165906351-1470e89f-65d7-4633-9f60-1afc3e2905c7.png)

backgroup header card nên màu xanh

**Comment by aloha1604** [comment]
![image](https://user-images.githubusercontent.com/46180709/165906612-c929b66e-62a7-4183-a5b2-a9071bed2869.png)
Hiện tại phân trang trên UI này không click được

**Comment by aloha1604** [comment]
Lúc edit : nên user search record vừa edit
