### ISSUE TITLE
Test  "Rules" screen 

### ISSUE THREAD

**Issue by vobachnhac1** [vobachnhac1/cb-web#18]

**Comment by aloha1604** [comment]
![image](https://user-images.githubusercontent.com/46180709/165919574-da2e2647-4210-49bb-aa8c-d02dd0d2ca8c.png)
chổ approve nên có 2 nút để phân biệt khi nào active khi nào inactive

**Comment by aloha1604** [comment]
![image](https://user-images.githubusercontent.com/46180709/165920302-0cf55e52-76f6-48f2-a533-c4b590157c20.png)
khi còn 1 record inactive thì nhân nut approve , a xem lại chổ này

**Comment by aloha1604** [comment]
![image](https://user-images.githubusercontent.com/46180709/165920507-bbb75bb8-5e6e-4836-8e18-c18c12d7c3e9.png)
nên hiển thị inactive luon cho người dung nhìn thấy được

**Comment by aloha1604** [comment]
![image](https://user-images.githubusercontent.com/46180709/165920862-e6e1fd3c-beb3-4a49-9db2-4bc7258292f1.png)
backEnd nhánh develop pull code mới về, nhưng nhấn add ko đc
