### ISSUE TITLE
Develop "Wheel-child" 

### ISSUE THREAD

**Issue by vobachnhac1** [vobachnhac1/cb-web#19]

**Comment by aloha1604** [comment]
![image](https://user-images.githubusercontent.com/46180709/165922117-b82e5fe2-540a-4b3e-972a-e41a5ed51a21.png)
vòng quay bị dính thanh croll

**Comment by aloha1604** [comment]
![image](https://user-images.githubusercontent.com/46180709/166653699-33bec4be-6847-4822-af48-d9ac63af30a1.png)
